name       : gnome-color-manager
version    : 3.36.0
release    : 15
source     :
    - https://download.gnome.org/sources/gnome-color-manager/3.36/gnome-color-manager-3.36.0.tar.xz : 9ddb9e6b6472e119801381f90905332ec1d4258981721bba831ca246ceb3ad3b
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Color Manager
description: |
    GNOME Color Manager is a set of graphical utilities for color management to be used in the GNOME desktop.
builddeps  :
    - pkgconfig(colord)
    - pkgconfig(exiv2)
    - pkgconfig(lcms2)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libtiff-4)
    - itstool
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
