name       : gnome-color-manager
version    : 3.22.2
release    : 4
source     :
    - https://download.gnome.org/sources/gnome-color-manager/3.22/gnome-color-manager-3.22.2.tar.xz : e837a184e66a6a5fb778730a58d3aa8d3a10a447e13f48efc86cac7e4c94d45b
license    : GPL-2.0
component  : desktop.gnome.core
summary    : GNOME Color Manager
description: |
    GNOME Color Manager is a set of graphical utilities for color management
    to be used in the GNOME desktop.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(colord)
    - pkgconfig(colord-gtk)
    - pkgconfig(vte-2.91)
    - pkgconfig(exiv2)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libexif)
    - pkgconfig(libtiff-4)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
