name       : gnome-color-manager
version    : 3.24.0
release    : 5
source     :
    - https://download.gnome.org/sources/gnome-color-manager/3.24/gnome-color-manager-3.24.0.tar.xz : a1009e6287d97b8d1fdd6e44a4c8668bcf05f1bb7f2186243318e54c6d061dd2
license    : GPL-2.0
component  : desktop.gnome.core
summary    : GNOME Color Manager
description: |
    GNOME Color Manager is a set of graphical utilities for color management
    to be used in the GNOME desktop.
builddeps  :
    - pkgconfig(colord)
    - pkgconfig(colord-gtk)
    - pkgconfig(exiv2)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libexif)
    - pkgconfig(libtiff-4)
    - pkgconfig(vte-2.91)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
