name       : gnome-color-manager
version    : 3.28.0
release    : 9
source     :
    - https://download.gnome.org/sources/gnome-color-manager/3.28/gnome-color-manager-3.28.0.tar.xz : ec333a9fa4688b29b0f4b6cabe941f7f40bfe9a1369ba75b7ffc185c8d7a3dd6
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Color Manager
description: |
    GNOME Color Manager is a set of graphical utilities for color management
    to be used in the GNOME desktop.
builddeps  :
    - pkgconfig(colord)
    - pkgconfig(colord-gtk)
    - pkgconfig(exiv2)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libexif)
    - pkgconfig(libtiff-4)
    - pkgconfig(vte-2.91)
    - itstool
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
