name       : gnome-color-manager
version    : 3.32.0
release    : 11
source     :
    - https://download.gnome.org/sources/gnome-color-manager/3.32/gnome-color-manager-3.32.0.tar.xz : 7c3c178faacfcbf11d56de22cd265946a7d58aa10e3cd968c2938e2fbf50fdee
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Color Manager
description: |
    GNOME Color Manager is a set of graphical utilities for color management
    to be used in the GNOME desktop.
builddeps  :
    - pkgconfig(colord)
    - pkgconfig(colord-gtk)
    - pkgconfig(exiv2)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libexif)
    - pkgconfig(libtiff-4)
    - pkgconfig(vte-2.91)
    - itstool
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
