name       : gnome-color-manager
version    : 3.20.0
release    : 2
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gnome-color-manager/3.20/gnome-color-manager-3.20.0.tar.xz : fc4b8b075e79c1633ad935fb42e2aa06bf31a3e7e15360c705c771366e540793
license    : GPL-2.0
component  : desktop.gnome.core
summary    : GNOME Color Manager
description: |
    GNOME Color Manager is a set of graphical utilities for color management
    to be used in the GNOME desktop.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(colord)
    - pkgconfig(colord-gtk)
    - pkgconfig(vte-2.91)
    - pkgconfig(exiv2)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libexif)
    - pkgconfig(libtiff-4)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
