name       : gnome-color-manager
version    : 3.26.0
release    : 8
source     :
    - https://download.gnome.org/sources/gnome-color-manager/3.26/gnome-color-manager-3.26.0.tar.xz : 652100e08520338b24218230f0586227879150d7d093ca637fc06130b72171cd
license    : GPL-2.0
component  : desktop.gnome.core
summary    : GNOME Color Manager
description: |
    GNOME Color Manager is a set of graphical utilities for color management
    to be used in the GNOME desktop.
builddeps  :
    - pkgconfig(colord)
    - pkgconfig(colord-gtk)
    - pkgconfig(exiv2)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libexif)
    - pkgconfig(libtiff-4)
    - pkgconfig(vte-2.91)
    - itstool
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
